/*
- Software Name: Truth Table Generator
- Version: 1.4
- Language: C
- Developer: Emilio Rivera Macías
- Contact: emilioriveramacias@gmail.com
Description:
    + Can solve logic expressions that have multiple parentheses ("()/{}/[]"), the expression can have or not have
    spaces between parentheses, variables and logic operators and solves logic operators like: union (U), intersection (^),
    conditional (->) and bidonditional (<->).
    + Supports memory deallocation so the application can be used multiple times to solve multiple expressions continually
    + Supports the negation (!) operator.
*/

// necessary headers ---------------------------->
#include "Expression_Solver.h"
#include "Menu.h"

// main code ---------------------------->
int main()
{
    // variable declaration ---------------------------->
    // stores all the variables from the logic expression
    struct Variable *variable_list = NULL;
    // stores all the sub logic expressions from the main logic expression
    struct Sub_Expression *sub_expression_list = NULL;
    // stores the logic expression inputted by the user
    char EXPRESSION[50];
    int option = 0;
    // Represents the total number of possible values (lines) the table will have
    int num_values = 1;
    do
    {
        // display program menu and get user input option
        option = menu();
        switch (option)
        {
        // input and solve a logic expression
        case 1:
            printf("\nWrite the logic expression -> ");
            scanf("%s", EXPRESSION);
            
            // generate the variable and sub expressions lists
            variable_list = set_variables(variable_list, EXPRESSION, &num_values);
            sub_expression_list = set_sub_expressions(sub_expression_list, EXPRESSION, num_values);

            // solve the logic expression
            expression_solver(sub_expression_list, variable_list, num_values);

            // output the truth table generated by expression_solver function
            write_variables(variable_list, num_values);
            write_sub_expresions(sub_expression_list, num_values);

            // memory deallocation of the created elements from the solved expression
            deallocate_variables(variable_list);
            deallocate_expressions(sub_expression_list);
            // restoring variables values to the initial ones
            num_values = 1;
            variable_list = NULL;
            sub_expression_list = NULL;
            break;
        // display the help information
        case 2:
            help();
            break;
        // exit program
        case 0:
            printf("\nGoodbye...\n");
            break;
        // case where the input is not valid
        default:
            printf("\n\t\t********** Invalid Option **********\n");
            break;
        }
    } while (option != 0);

    return 0;
}